#!/usr/bin/env bash
# Maintainer tool: compute the hashes in artifacts.env from the upstream release assets, for the
# versions in ../../versions.env. Review the diff before committing. Needs network access.
#   pin.sh           write artifacts.env
#   pin.sh --check   fail if artifacts.env differs from what upstream serves now
# shellcheck shell=bash
# shellcheck source=../../lib/common.sh
LAB_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
export LAB_DIR
. "$LAB_DIR/../lib/common.sh"
need curl sha256sum awk

enc() { printf '%s' "${1//+/%2B}"; }
start=$(enc "$RKE2_VERSION_START")
up=$(enc "$RKE2_VERSION_UPGRADE")
rel=https://github.com/rancher/rke2/releases/download
raw=https://raw.githubusercontent.com/rancher/rke2
suc=https://github.com/rancher/system-upgrade-controller/releases/download/$SUC_VERSION
kured_tag=1.23.0

h() { curl -fsSL --retry 3 "$1" | sha256sum | awk '{print $1}'; }
tarball_hash() { curl -fsSL --retry 3 "$rel/$1/sha256sum-amd64.txt" | awk '$2=="rke2.linux-amd64.tar.gz"{print $1}'; }

install_start=$(h "$raw/$start/install.sh")
install_up=$(h "$raw/$up/install.sh")
[ "$install_start" = "$install_up" ] || die "install.sh differs between $RKE2_VERSION_START and $RKE2_VERSION_UPGRADE: pin one per version"

out=$(cat <<ENV
# Pinned artifacts for lab 05. Generated by scripts/pin.sh from the upstream release assets for the
# versions in ../../versions.env (RKE2 $RKE2_VERSION_START -> $RKE2_VERSION_UPGRADE, SUC $SUC_VERSION,
# kured $kured_tag). Re-run it and review the diff whenever a version changes.
# Values are SHA-256 digests. Tags are URL-encoded in download URLs ("+" becomes "%2B").
#
# install.sh at both RKE2 tags (verified identical when generated)
RKE2_INSTALL_SH_SHA256=$install_start
# start version: tarball and its sha256sum-amd64.txt
RKE2_START_TARBALL_SHA256=$(tarball_hash "$start")
RKE2_START_SUMS_SHA256=$(h "$rel/$start/sha256sum-amd64.txt")
# upgrade version
RKE2_UPGRADE_TARBALL_SHA256=$(tarball_hash "$up")
# add-on manifests applied by \`lab05.sh addons\`, hash-checked before kubectl sees them
SUC_CRD_SHA256=$(h "$suc/crd.yaml")
SUC_DEPLOY_SHA256=$(h "$suc/system-upgrade-controller.yaml")
KURED_RBAC_SHA256=$(h "https://raw.githubusercontent.com/kubereboot/kured/$kured_tag/kured-rbac.yaml")
ENV
)

case ${1:-} in
--check)
    if [ "$out" = "$(cat "$LAB_DIR/artifacts.env")" ]; then log "artifacts.env is up to date"; else
        diff <(printf '%s\n' "$out") "$LAB_DIR/artifacts.env" || true
        die "artifacts.env differs from upstream"
    fi
    ;;
"")
    printf '%s\n' "$out" >"$LAB_DIR/artifacts.env"
    log "wrote $LAB_DIR/artifacts.env"
    ;;
*) die "usage: $0 [--check]" ;;
esac
